---
cluster:
  nodes:
  - internal: '3000'
    external: '5000'
    host: 127.0.0.1
  - internal: '3001'
    external: '5001'
    host: 127.0.0.1
  - internal: '3002'
    external: '5002'
    host: 127.0.0.1
  - internal: '3003'
    external: '5003'
    host: 127.0.0.1
  - internal: '3004'
    external: '5004'
    host: 127.0.0.1
